version: "3.7"

services:
    # image project
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8084:8000"
        command: "php artisan serve --host 0.0.0.0"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        build: .
        restart: always
        ports:
            - '8083:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
            # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: comunidade_de_cristo
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_PASSWORD: 1234
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
            # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
